version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}  
    env_file:
      - .env                    
    volumes:
      - .:/usr/src/app            # Syncs the local code with the container